name: Rust CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/rust-build.yml@rust-build-v2.1.0
    with:
      rust-version: '1.94.0'
      working-directory: "."
      enable-cache: true
      publish-crates-io: false

  prepare:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: |
      github.repository_owner == 'iExec-Nox' &&
      (github.ref_name == 'main' ||
       startsWith(github.head_ref, 'feat/') ||
       startsWith(github.head_ref, 'fix/') ||
       (github.event_name == 'workflow_dispatch' && (startsWith(github.ref_name, 'feat/') || startsWith(github.ref_name, 'fix/'))))
    outputs:
      image_tag: ${{ steps.determine-tag.outputs.image_tag }}
    steps:
      - name: Determine base tag
        id: determine-tag
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ] ; then
            SHORT_SHA="$(echo ${{ github.event.pull_request.head.sha }} | cut -c1-8)"
            GIT_BRANCH="${{ github.head_ref }}"
          else
            SHORT_SHA="$(echo ${{ github.sha }} | cut -c1-8)"
            GIT_BRANCH="${{ github.ref_name }}"
          fi

          if [ "${{ github.ref_name }}" = "main" ] ; then
            echo "Processing main branch"
            echo "image_tag=dev-${SHORT_SHA}" | tee -a $GITHUB_OUTPUT
          else
            # This covers feat/ and fix/ branches
            echo "Processing feat/fix branch $GIT_BRANCH"
            echo "image_tag=feature-${SHORT_SHA}" | tee -a $GITHUB_OUTPUT
          fi

  build-oci-image:
    name: Build OCI image
    needs: prepare
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/docker-build.yml@docker-build-v3.3.0
    with:
      image-name: docker-regis.iex.ec/nox-runner
      image-tag: ${{ needs.prepare.outputs.image_tag }}
      dockerfile: Dockerfile
      context: .
      registry: docker-regis.iex.ec
      push: true
      security-scan: true
      security-report: "comment"
      hadolint: true
      platform: linux/amd64
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN_PULL_ONLY }}
      username: ${{ secrets.DOCKERREGIS_USERNAME }}
      password: ${{ secrets.DOCKERREGIS_PASSWORD }}
